[package]
name = "vram-lock"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
env_logger = "0.11.8"
pollster = "0.4.0"
rand = "0.9.2"
rustfmt = "0.10.0"
sprs = "0.11.4"
tokio = "1.48.0"
wgpu = "27.0.1"
